"""Import all data sources referenced and generated by api_export.py into MongoDB.

MongoDB URI: mongodb://admin:12345678@localhost:27017/
Database: bank_risk_db
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path
from datetime import datetime
from pymongo import MongoClient

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
BANK_RISK_SERVICE_DIR = PROJECT_ROOT / "bank_risk_service"
if str(BANK_RISK_SERVICE_DIR) not in sys.path:
    sys.path.insert(0, str(BANK_RISK_SERVICE_DIR))
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data_loader import load_all, missing_metric_table
from src.pipeline import available_frequencies, run_pipeline
from src.api_export import (
    build_meta,
    build_performance,
    build_pdf_status,
    build_payload,
    export_frequency,
    _clean
)
from src.utils import DATA_ROOT, LOG, load_config

MONGO_URI = os.getenv("MONGO_URI", "mongodb://admin:12345678@localhost:27018/")
DB_NAME = "bank_risk_db"


def get_mongo_client():
    uris = [
        os.getenv("MONGO_URI"),
        "mongodb://admin:12345678@localhost:27018/",
        "mongodb://admin:12345678@localhost:27017/",
    ]
    for u in uris:
        if not u:
            continue
        try:
            c = MongoClient(u, serverSelectionTimeoutMS=2000)
            c.admin.command("ping")
            print(f"Connected to MongoDB at {u}")
            return c
        except Exception:
            continue
    raise RuntimeError("Could not connect to MongoDB on port 27018 or 27017")


def sanitize_dict_or_list(obj):
    """Recursively clean dict/list objects for BSON compliance."""
    if isinstance(obj, dict):
        return {str(k): sanitize_dict_or_list(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [sanitize_dict_or_list(v) for v in obj]
    else:
        return _clean(obj)


def import_all_to_mongodb():
    start_time = time.time()
    client = get_mongo_client()
    db = client[DB_NAME]
    
    print(f"Target Database: '{DB_NAME}'")
    
    # ----------------------------------------------------
    # 1. Raw Ingested Data & Files
    # ----------------------------------------------------
    print("\n--- 1. Ingesting Raw Panel Data & File Metadata ---")
    load_res = load_all(DATA_ROOT, use_cache=True)
    
    # Raw Panel Data (long form)
    if load_res.panel is not None and not load_res.panel.empty:
        coll = db["raw_panel_data"]
        coll.drop()
        panel_records = load_res.panel.to_dict(orient="records")
        for r in panel_records:
            sf = str(r.get("source_file") or "")
            if sf and not sf.startswith("bankrisk-files/"):
                r["source_file"] = f"bankrisk-files/{sf}"
            if "source_file_full_path" in r:
                del r["source_file_full_path"]
        cleaned_panel = [sanitize_dict_or_list(r) for r in panel_records]
        if cleaned_panel:
            coll.insert_many(cleaned_panel)
            coll.create_index([("bank_id", 1), ("period", 1), ("frequency", 1)])
            print(f"  [+] Imported {len(cleaned_panel)} documents into 'raw_panel_data'")
            
    # File Metadata
    if load_res.files:
        coll = db["raw_files"]
        coll.drop()
        cleaned_files = [sanitize_dict_or_list(f) for f in load_res.files]
        coll.insert_many(cleaned_files)
        print(f"  [+] Imported {len(cleaned_files)} documents into 'raw_files'")
        
    # Unmapped Labels
    if load_res.unmapped_labels:
        coll = db["unmapped_labels"]
        coll.drop()
        unmapped_recs = [{"label": k, "count": int(v)} for k, v in load_res.unmapped_labels.items()]
        coll.insert_many(unmapped_recs)
        print(f"  [+] Imported {len(unmapped_recs)} documents into 'unmapped_labels'")

    # ----------------------------------------------------
    # 2. Side & Metadata Payloads
    # ----------------------------------------------------
    print("\n--- 2. Ingesting Metadata, Configurations, PDF status & Performance ---")
    
    # Metadata
    meta_payload = build_meta()
    coll = db["pipeline_meta"]
    coll.drop()
    coll.insert_one(sanitize_dict_or_list(meta_payload))
    print("  [+] Imported metadata into 'pipeline_meta'")

    # Regulatory Rules Config
    rules_cfg = load_config("regulatory_rules").get("rules", [])
    if rules_cfg:
        coll = db["regulatory_rules_config"]
        coll.drop()
        cleaned_rules = [sanitize_dict_or_list(r) for r in rules_cfg]
        coll.insert_many(cleaned_rules)
        coll.create_index([("rule_id", 1)])
        print(f"  [+] Imported {len(cleaned_rules)} rules into 'regulatory_rules_config'")

    # Performance & Feedback
    perf = build_performance()
    coll_log = db["performance_logs"]
    coll_log.drop()
    if perf.get("log"):
        coll_log.insert_many([sanitize_dict_or_list(r) for r in perf["log"]])
        print(f"  [+] Imported {len(perf['log'])} log entries into 'performance_logs'")
        
    coll_fb = db["user_feedback"]
    coll_fb.drop()
    if perf.get("feedback"):
        coll_fb.insert_many([sanitize_dict_or_list(r) for r in perf["feedback"]])
        print(f"  [+] Imported {len(perf['feedback'])} feedback entries into 'user_feedback'")

    coll_sug = db["performance_suggestions"]
    coll_sug.drop()
    if perf.get("suggestions"):
        coll_sug.insert_many([sanitize_dict_or_list(r) for r in perf["suggestions"]])
        print(f"  [+] Imported {len(perf['suggestions'])} suggestions into 'performance_suggestions'")

    # PDF Status & Rule Candidates
    pdf_stat = build_pdf_status()
    coll_pdf_files = db["pdf_file_status"]
    coll_pdf_files.drop()
    if pdf_stat.get("file_status"):
        coll_pdf_files.insert_many([sanitize_dict_or_list(r) for r in pdf_stat["file_status"]])
        print(f"  [+] Imported {len(pdf_stat['file_status'])} PDF status records into 'pdf_file_status'")

    coll_pdf_cand = db["pdf_rule_candidates"]
    coll_pdf_cand.drop()
    if pdf_stat.get("candidates"):
        coll_pdf_cand.insert_many([sanitize_dict_or_list(r) for r in pdf_stat["candidates"]])
        print(f"  [+] Imported {len(pdf_stat['candidates'])} PDF candidates into 'pdf_rule_candidates'")

    # ----------------------------------------------------
    # 3. Frequency Analysis Payloads
    # ----------------------------------------------------
    frequencies = available_frequencies(DATA_ROOT)
    print(f"\n--- 3. Ingesting Frequency Payloads: {frequencies} ---")
    
    # Collections to hold data across frequencies
    coll_rankings = db["bank_rankings"]
    coll_rankings.drop()
    
    coll_scores = db["risk_scores"]
    coll_scores.drop()
    
    coll_rule_findings = db["rule_findings"]
    coll_rule_findings.drop()
    
    coll_anomalies = db["anomalies"]
    coll_anomalies.drop()
    
    coll_clusters = db["clusters"]
    coll_clusters.drop()
    
    coll_stress_sys = db["systemic_stress"]
    coll_stress_sys.drop()
    
    coll_high_risk = db["high_risk_periods"]
    coll_high_risk.drop()
    
    coll_ews = db["ews_indicators"]
    coll_ews.drop()
    
    coll_stress = db["stress_test_results"]
    coll_stress.drop()
    
    coll_validation = db["validation_findings"]
    coll_validation.drop()

    coll_summaries = db["frequency_summaries"]
    coll_summaries.drop()

    for freq in frequencies:
        print(f"\nProcessing frequency: '{freq}'...")
        export_frequency(freq, use_cache=True)
        payload = build_payload(freq, use_cache=True)
        if payload.get("empty"):
            print(f"  [!] Frequency '{freq}' payload is empty. Skipping...")
            continue

        # Summary
        summary = payload.get("summary", {})
        summary["frequency"] = freq
        summary["generated_at"] = payload.get("generated_at")
        coll_summaries.insert_one(sanitize_dict_or_list(summary))

        # Ranking
        ranking = payload.get("ranking", [])
        for r in ranking:
            r["frequency"] = freq
        if ranking:
            coll_rankings.insert_many([sanitize_dict_or_list(r) for r in ranking])
            print(f"  [+] Inserted {len(ranking)} rankings for '{freq}'")

        # Risk Scores
        scores = payload.get("scores", [])
        for s in scores:
            s["frequency"] = freq
        if scores:
            coll_scores.insert_many([sanitize_dict_or_list(s) for s in scores])
            print(f"  [+] Inserted {len(scores)} risk scores for '{freq}'")

        # Rule Findings
        findings = payload.get("rule_findings", [])
        for f in findings:
            f["frequency"] = freq
        if findings:
            coll_rule_findings.insert_many([sanitize_dict_or_list(f) for f in findings])
            print(f"  [+] Inserted {len(findings)} rule findings for '{freq}'")

        # Anomalies
        anomalies = payload.get("anomalies", [])
        for a in anomalies:
            a["frequency"] = freq
        if anomalies:
            coll_anomalies.insert_many([sanitize_dict_or_list(a) for a in anomalies])
            print(f"  [+] Inserted {len(anomalies)} anomalies for '{freq}'")

        # Cluster metadata / profiles
        clusters_data = payload.get("clusters", {})
        if clusters_data:
            cluster_doc = {
                "frequency": freq,
                "k": clusters_data.get("k"),
                "metrics": clusters_data.get("metrics"),
                "profiles": clusters_data.get("profiles"),
                "projection": clusters_data.get("projection"),
                "assignment": clusters_data.get("assignment")
            }
            coll_clusters.insert_one(sanitize_dict_or_list(cluster_doc))
            print(f"  [+] Inserted cluster model payload for '{freq}'")

        # Systemic Stress
        sys_stress = payload.get("systemic_stress", [])
        for ss in sys_stress:
            ss["frequency"] = freq
        if sys_stress:
            coll_stress_sys.insert_many([sanitize_dict_or_list(ss) for ss in sys_stress])
            print(f"  [+] Inserted {len(sys_stress)} systemic stress records for '{freq}'")

        # High Risk Periods
        hr_periods = payload.get("high_risk_periods", [])
        for hr in hr_periods:
            hr["frequency"] = freq
        if hr_periods:
            coll_high_risk.insert_many([sanitize_dict_or_list(hr) for hr in hr_periods])
            print(f"  [+] Inserted {len(hr_periods)} high risk period alerts for '{freq}'")

        # EWS Payload
        ews_data = payload.get("ews", {})
        if ews_data:
            ews_doc = {
                "frequency": freq,
                "metrics_used": ews_data.get("metrics_used"),
                "level_counts": ews_data.get("level_counts"),
                "system_now": ews_data.get("system_now"),
                "latest": ews_data.get("latest"),
                "system": ews_data.get("system"),
                "emerging": ews_data.get("emerging"),
                "trajectory": ews_data.get("trajectory"),
                "table": ews_data.get("table")
            }
            coll_ews.insert_one(sanitize_dict_or_list(ews_doc))
            print(f"  [+] Inserted EWS payload for '{freq}'")

        # Stress Payload
        stress_data = payload.get("stress", {})
        if stress_data:
            stress_doc = {
                "frequency": freq,
                "snapshot_period": stress_data.get("snapshot_period"),
                "scenarios": stress_data.get("scenarios"),
                "system": stress_data.get("system"),
                "results": stress_data.get("results"),
                "breaking_points": stress_data.get("breaking_points")
            }
            coll_stress.insert_one(sanitize_dict_or_list(stress_doc))
            print(f"  [+] Inserted stress test payload for '{freq}'")

        # Validation Findings
        val_findings = payload.get("validation", [])
        for v in val_findings:
            v["frequency"] = freq
        if val_findings:
            coll_validation.insert_many([sanitize_dict_or_list(v) for v in val_findings])
            print(f"  [+] Inserted {len(val_findings)} validation findings for '{freq}'")

    # ----------------------------------------------------
    # 4. Create Indexes
    # ----------------------------------------------------
    print("\n--- 4. Creating Database Indexes ---")
    coll_rankings.create_index([("bank_id", 1), ("period", 1), ("frequency", 1)])
    coll_scores.create_index([("bank_id", 1), ("period", 1), ("frequency", 1)])
    coll_rule_findings.create_index([("bank_id", 1), ("period", 1), ("frequency", 1), ("rule_id", 1)])
    coll_rule_findings.create_index([("severity", 1)])
    coll_anomalies.create_index([("bank_id", 1), ("period", 1), ("frequency", 1)])
    print("  [+] Indexes created successfully.")

    elapsed = time.time() - start_time
    print(f"\n=======================================================")
    print(f" SUCCESSFULLY IMPORTED ALL API_EXPORT DATA TO MONGODB")
    print(f" Total Execution Time: {elapsed:.2f} seconds")
    print(f" Database Name: {DB_NAME}")
    print(f" Collections in '{DB_NAME}':")
    for name in sorted(db.list_collection_names()):
        count = db[name].count_documents({})
        print(f"   - {name:<30}: {count:>8} docs")
    print(f"=======================================================")


if __name__ == "__main__":
    import_all_to_mongodb()
